config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  get 'mascotas/index', to: 'mascotas#index'
  get 'mascotas/new', to: 'mascotas#new'
  post 'mascotas/', to: 'mascotas#create'
  get 'mascotas/:id', to: 'mascotas#show', as: 'mascota'
  get 'mascotas/:id/edit', to: 'mascotas#edit', as: 'mascotas_edit'
  patch 'mascotas/:id', to: 'mascotas#update'
  put 'mascotas/:id', to: 'mascotas#update'

  delete 'mascotas/:id(.:format)', :to => 'mascotas#destroy'

  get 'perros/index', to: 'perros#index'
  get 'perros/new', to: 'perros#new'
  post 'perros/', to: 'perros#create'
  get 'perros/:id', to: 'perros#show', as: 'perro'
  get 'perros/:id/edit', to: 'perros#edit', as: 'perros_edit'
  patch 'perros/:id', to: 'perros#update'
  put 'perros/:id', to: 'perros#update'

  delete 'perros/:id(.:format)', :to => 'perros#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
end

app/models/flor.rb
class Flor < ApplicationRecord
end

app/models/frutum.rb
class Frutum < ApplicationRecord
end

app/models/lib.rb
class Lib < ApplicationRecord
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/models/mascotum.rb
class Mascotum < ApplicationRecord
end

app/models/pencil.rb
class Pencil < ApplicationRecord
end

app/models/perro.rb
class Perro < ApplicationRecord
  
end

app/controllers/libs_controller.rb
class LibsController < ApplicationController
  before_action :set_lib, only: [:show, :edit, :update, :destroy]

  # GET /libs
  # GET /libs.json
  def index
    @libs = Lib.all
  end

  # GET /libs/1
  # GET /libs/1.json
  def show
  end

  # GET /libs/new
  def new
    @lib = Lib.new
  end

  # GET /libs/1/edit
  def edit
  end

  # POST /libs
  # POST /libs.json
  def create
    @lib = Lib.new(lib_params)

    respond_to do |format|
      if @lib.save
        format.html { redirect_to @lib, notice: 'Lib was successfully created.' }
        format.json { render :show, status: :created, location: @lib }
      else
        format.html { render :new }
        format.json { render json: @lib.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libs/1
  # PATCH/PUT /libs/1.json
  def update
    respond_to do |format|
      if @lib.update(lib_params)
        format.html { redirect_to @lib, notice: 'Lib was successfully updated.' }
        format.json { render :show, status: :ok, location: @lib }
      else
        format.html { render :edit }
        format.json { render json: @lib.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libs/1
  # DELETE /libs/1.json
  def destroy
    @lib.destroy
    respond_to do |format|
      format.html { redirect_to libs_url, notice: 'Lib was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lib
      @lib = Lib.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lib_params
      params.require(:lib).permit(:nombre, :descrip)
    end
end

app/controllers/perros_controller.rb
class PerrosController < ApplicationController
    def index
        @pers = Perro.all
    end

    def new
        @pers = Perro.new
    end

    def create
        @pers = Perro.new(perros_params)
        if @pers.save
            redirect_to perros_index_path
        else
            render :edit
        end
    end

    def edit
        @pers = Perro.find(params[:id])
    end
    def update
        @pers = Perro.find(params[:id])
        if @pers.update(perros_params)
            redirect_to perros_index_path
        else
            render :edit
        end
    end

    def destroy
        @pers = Perro.find(params[:id])
        if @pers.destroy
            redirect_to perros_index_path
        end
    end

    def perros_params
        params.require(:perro).permit(:nombre,:descrip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/flores_helper.rb
module FloresHelper
end

app/helpers/frutas_helper.rb
module FrutasHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/libs_helper.rb
module LibsHelper
end

app/helpers/mascotas_helper.rb
module MascotasHelper
end

app/helpers/pencils_helper.rb
module PencilsHelper
end

app/helpers/perros_helper.rb
module PerrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/perros/edit.html.erb
<%= form_for @pers do |f|%>

    <div class="form-group">
        <%= f.label :nombre %>
        <%= f.text_field :nombre %>
    </div>
    <div class="form-group">
        <%= f.label :descrip %>
        <%= f.text_field :descrip %>
    </div>
    <div class="form-group">
        <%= f.submit %>
    </div>
<% end%>

app/views/perros/index.html.erb
<div class="container">
    <div class="p4">
        <table class="table table-hover">
            <thead class="bg-primary">
                <tr>
                    <td> Nombre </td>
                    <td> descripcion </td>
                    <td> <%= link_to "New",perros_new_path,class:"btn btn-primary"%> </td>
                </tr>
            </thead>
            <tbody>
                <% @pers.each do |perro|%>
                    
                <tr>
                    <td> <%= perro.nombre%> </td>
                    <td> <%= perro.descrip%> </td>
                    <td> <%= link_to "edit",perros_edit_path(perro),class:"btn btn-primary"%> 
                    <%= link_to "delete",perro,method: :delete, data: { confirm: "desea eliminarlo"} , class:"btn btn-danger"%> </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/perros/new.html.erb
<%= form_for @pers do |f|%>

    <div class="form-group">
        <%= f.label :nombre %>
        <%= f.text_field :nombre %>
    </div>
    <div class="form-group">
        <%= f.label :descrip %>
        <%= f.text_field :descrip %>
    </div>
    <div class="form-group">
        <%= f.submit %>
    </div>
<% end%>