config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  get 'mascotas/index', to: 'mascotas#index'
  get 'mascotas/new', to: 'mascotas#new'
  post 'mascotas/', to: 'mascotas#create'
  get 'mascotas/:id', to: 'mascotas#show', as: 'mascota'
  get 'mascotas/:id/edit', to: 'mascotas#edit', as: 'mascotas_edit'
  patch 'mascotas/:id', to: 'mascotas#update'
  put 'mascotas/:id', to: 'mascotas#update'

  delete 'mascotas/:id(.:format)', :to => 'mascotas#destroy'

  get 'perros/index', to: 'perros#index'
  get 'perros/new', to: 'perros#new'
  post 'perros/', to: 'perros#create'
  get 'perros/:id', to: 'perros#show', as: 'perro'
  get 'perros/:id/edit', to: 'perros#edit', as: 'perros_edit'
  patch 'perros/:id', to: 'perros#update'
  put 'perros/:id', to: 'perros#update'

  delete 'perros/:id(.:format)', :to => 'perros#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
end

app/models/flor.rb
class Flor < ApplicationRecord
end

app/models/frutum.rb
class Frutum < ApplicationRecord
end

app/models/lib.rb
class Lib < ApplicationRecord
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/models/mascotum.rb
class Mascotum < ApplicationRecord
end

app/models/pencil.rb
class Pencil < ApplicationRecord
end

app/models/perro.rb
class Perro < ApplicationRecord
  
end

app/controllers/mascotas_controller.rb
class MascotasController < ApplicationController
    def index
        @mascotas = Mascotum.all
    end

    def new
        @mascotas = Mascotum.new 
    end

    def create
        @mascotas = Mascotum.new(pro_params)
        if @mascotas.save
        redirect_to mascotas_index_path
        else
           render :new
        end
    end

    def edit
        @mascotas = Mascotum.find(params[:id]) 
    end

    def update
        @mascotas = Mascotum.find(params[:id])
        if @mascotas.update(pro_params)
        redirect_to mascotas_index_path
        else
           render :edit
        end
    end

    def destroy
        @mascotas = Mascotum.find(params[:id])
        if @mascotas.destroy
        redirect_to mascotas_index_path
        end
    end


    def pro_params
        params.require(:mascotum).permit(:nombre,:descrip,:cantidad)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/helpers/flores_helper.rb
module FloresHelper
end

app/helpers/frutas_helper.rb
module FrutasHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/libs_helper.rb
module LibsHelper
end

app/helpers/mascotas_helper.rb
module MascotasHelper
end

app/helpers/pencils_helper.rb
module PencilsHelper
end

app/helpers/perros_helper.rb
module PerrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/mascotas/edit.html.erb
<%= form_for @mascotas do |f|%>

<div class="container">
    <div class="p-4">
        <div class="form-group">
        <%= f.label :nombre%>
        <%= f.text_field :nombre%>
        </div>
        <div class="form-group">
        <%= f.label :descrip%>
        <%= f.area_field :descrip%>
        </div>
        <div class="form-group">
        <%= f.label :cantidad%>
        <%= f.number_field :cantidad%>
        </div>
        <div class="form-group">
        <%= f.submit %>
        </div>
    </div>

</div>


<% end %>

app/views/mascotas/index.html.erb
<div class="container">
    <div class="p-4">
        <table class="table">
            <thead class="bg-primary">
                <tr>
                    <td>Nombre </td>
                    <td>Descripcion </td>
                    <td>Cantidad </td>
                    <td> <%= link_to "New" ,mascotas_new_path,class:"btn btn-primary"%> </td>
                </tr>
            </thead>
            <tbody>
                <% @mascotas.each do |masco|%>
                <tr>
                   <td><%= masco.nombre%> </td>
                    <td><%= masco.descrip%>  </td>
                    <td><%= masco.cantidad%>  </td>
                    <td> <%= link_to "Edit" ,mascotas_edit_path(masco),class:"btn btn-primary"%>
                        <%# <%= link_to "Eliminar" ,masco, method: :delete, data: { confirm: "Deseas eliminar esta mascota?"}  ,class:"btn btn-danger"%>
                     </td> 
                      </tr>
                <% end %>
            </tbody>
        </table>
    </div>

</div>

app/views/mascotas/new.html.erb
<%= form_for @mascotas do |f|%>

<div class="container">
    <div class="p-4">
        <div class="form-group">
        <%= f.label :nombre%>
        <%= f.text_field :nombre%>
        </div>
        <div class="form-group">
        <%= f.label :descrip%>
        <%= f.area_field :descrip%>
        </div>
        <div class="form-group">
        <%= f.label :cantidad%>
        <%= f.number_field :cantidad%>
        </div>
        <div class="form-group">
        <%= f.submit %>
        </div>
    </div>

</div>


<% end %>