config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  get 'mascotas/index', to: 'mascotas#index'
  get 'mascotas/new', to: 'mascotas#new'
  post 'mascotas/', to: 'mascotas#create'
  get 'mascotas/:id', to: 'mascotas#show', as: 'mascota'
  get 'mascotas/:id/edit', to: 'mascotas#edit', as: 'mascotas_edit'
  patch 'mascotas/:id', to: 'mascotas#update'
  put 'mascotas/:id', to: 'mascotas#update'

  delete 'mascotas/:id(.:format)', :to => 'mascotas#destroy'

  get 'perros/index', to: 'perros#index'
  get 'perros/new', to: 'perros#new'
  post 'perros/', to: 'perros#create'
  get 'perros/:id', to: 'perros#show', as: 'perro'
  get 'perros/:id/edit', to: 'perros#edit', as: 'perros_edit'
  patch 'perros/:id', to: 'perros#update'
  put 'perros/:id', to: 'perros#update'

  delete 'perros/:id(.:format)', :to => 'perros#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
end

app/models/flor.rb
class Flor < ApplicationRecord
end

app/models/frutum.rb
class Frutum < ApplicationRecord
end

app/models/lib.rb
class Lib < ApplicationRecord
end

app/models/libro.rb
class Libro < ApplicationRecord
end

app/models/mascotum.rb
class Mascotum < ApplicationRecord
end

app/models/pencil.rb
class Pencil < ApplicationRecord
end

app/models/perro.rb
class Perro < ApplicationRecord
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/flores_helper.rb
module FloresHelper
end

app/helpers/frutas_helper.rb
module FrutasHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/helpers/libs_helper.rb
module LibsHelper
end

app/helpers/mascotas_helper.rb
module MascotasHelper
end

app/helpers/pencils_helper.rb
module PencilsHelper
end

app/helpers/perros_helper.rb
module PerrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Inicio",welcome_index_path ,class:"btn navbar-brand bg-dark" %>
 <div class="container">
    <%= link_to "Mascotas",mascotas_index_path ,class:"btn navbar-brand bg-dark mr-right" %>
    <%= link_to "Perro",perros_index_path ,class:"btn navbar-brand bg-dark mr-right" %>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mascotas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>